spring:
  cloud:
    gateway:
      routes:
      - id: micro1
        uri: http://localhost:8081/
        predicates:
        - Path=/micro1/**
      - id: micro2
        uri: http://localhost:8082/
        predicates:
        - Path=/micro2/**
        filters:
        - AddResponseHeader=Routed-Through, Toans Spring Cloud Gateway  